### ISSUE TITLE
WebSocketApp.close() raises AttributeError: 'NoneType' object has no attribute 'close_frame' (regression in 1.9.1)

### ISSUE THREAD

**Issue by r-madsen-qdi** [websocket-client/websocket-client#1055]
This is a small example reproducing the issue [repro_close_frame.py](https://github.com/user-attachments/files/31643824/repro_close_frame.py)

close() reads self.sock twice — once to guard, once after self.sock.close(**kwargs) has returned:

# websocket/_app.py:207
self.keep_running = False
if self.sock:
    self.sock.close(**kwargs)
    if self.sock.close_frame is not None:   # ← line 211
        self.last_close_frame = self.sock.close_frame
    self.sock = None

WebSocket.close() (_core.py:538) sets connected = False, sends the CLOSE frame, then blocks in a recv_frame() loop for up to timeout=3 seconds awaiting the peer's echo. During that
window the run_forever() thread's own recv fails and reaches teardown(), which sets self.sock = None (_app.py:387). Line 211 then dereferences None.

teardown() already handles this correctly, and its comment states the reason:

# _app.py:385
current_sock = self.sock
self.sock = None      # cleared BEFORE close, for multithreaded safety
current_sock.close()

close() didn't get the same treatment.

Introduced by 10d9159af ("Improve close frame handling to fix #1043 and add tests", #1044, 2026-01-27), shipped in 1.9.1 (2026-08-29). The test added alongside it,
test_client_initiated_close_captures_peer_close_frame, drives close() with self.sock = mock.Mock(); a mock's close() doesn't null app.sock, so the single-threaded test passes and the
concurrent path is uncovered.

Repro (attached): 21/25 on 1.9.1, 0/25 on 1.9.0, Python 3.12.3.

Suggested fix — capture into a local, matching teardown():

self.keep_running = False
sock = self.sock
if sock:

**Comment by engn33r** [comment]
Thank you for reporting this. This looks like a legitimate bug, I will aim to resolve this very soon

**Comment by engn33r** [comment]
Resolved by #1057 and should be fixed in release 1.9.2
