### PR TITLE
Fix race in WebSocketApp.close() when run_forever thread clears sock

### LINKED ISSUE #1056: version 1.9.1 now crashes with AttributeError in WebSocketApp.close()
In version 1.9.0 the `WebSocketApp.close()` method looked like this
```
    def close(self, **kwargs) -> None:
        """
        Close websocket connection.
        """
        self.keep_running = False
        if self.sock:
            self.sock.close(**kwargs)
            self.sock = None
```

In version 1.9.1 this method now looks like this
```
    def close(self, **kwargs: Any) -> None:
        """
        Close websocket connection.
        """
        self.keep_running = False
        if self.sock:
            self.sock.close(**kwargs)
            # Capture the peer's close frame before clearing socket reference
            if self.sock.close_frame is not None:
                self.last_close_frame = self.sock.close_frame
            self.sock = None
```

The `if self.sock.close_frame is not None` is now crashing with an `AttributeError`. I'm a developer for TrueNAS and we have used this library to underpin our Websocket client and our CI/CD has now started to crash here at this line. Our client runs `run_forever()` in a background thread and when we call our own `Client.close()` it calls `WebSocketApp.close()` from the main thread. While `self.sock.close(**kwargs)` is doing the close handshake, the background thread notices the connection closing and runs `teardown()`.  When the main thread comes back and evaluates `self.sock.close_frame`, the `self.sock` attribute is now `None`

For posterity, here is what our traceback looks like that we're seeing in our CI/CD.
```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/master/clean/jenkins/scripts/builder_orchestrator.py", line 2362, in <module>
    main()
    ~~~~^^
  File "/var/lib/jenkins/workspace/master/clean/jenkins/scripts/builder_orchestrator.py", line 2358, in main
    client.close()
    ~~~~~~~~~~~~^^
  File "/var/lib/jenkins/workspace/master/clean/.venv/lib/python3.13/site-packages/truenas_api_client/__init__.py", line 1008, in close
    self._ws.close()
    ~~~~~~~~~~~~~~^^
  File "/var/lib/jenkins/workspace/master/clean/.venv/lib/python3.13/site-packages/truenas_api_client/__init__.py", line 220, in close
    self.app.close()
    ~~~~~~~~~~~~~~^^
  File "/var/lib/jenkins/workspace/master/clean/.venv/lib/python3.13/site-packages/websocket/_app.py", line 211, in close
    if self.sock.close_frame is not None:
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close_frame'

### PR DESCRIPTION
**Pull request by yocalebo**
Version 1.9.1 introduced a crash when WebSocketApp.close() is called from a different thread than the one running run_forever(). Commit 10d9159 (PR #1044) changed close() so that it reads self.sock.close_frame after calling self.sock.close(). While self.sock.close() is waiting for the close handshake to finish, the run_forever() thread notices the connection is closing, runs teardown() and sets self.sock to None. When close() then reads self.sock.close_frame it raises AttributeError because self.sock is gone. Versions up to 1.9.0 never touched self.sock again after closing it, so this crash could not happen there. The fix is for close() to keep a local reference to the socket and use that for the whole method, so it never reads self.sock after another thread has cleared it.

Fixes #1056

### CODE REVIEW

**Comment by yocalebo** [comment]
Interestingly enough, after looking at other open PRs on this repo I've noticed this PR that has been rotting with no input/review https://github.com/websocket-client/websocket-client/pull/1046. It pointed out the same regression and tried to fix it using a lock.

**Comment by engn33r** [comment]
This PR fixes #1056 and #1055 (they report the same issue). As mentioned above, the issue was introduced in #1044, so only release 1.9.1 is affected. Release 1.9.2 will include this PR and resolve the issue.

The original PR resolves the issue, but I added a regression test to help prevent this issue from reappearing in the future.
